### ISSUE TITLE
CAPH crashes repeatedly when 'unable to get Xxx HostAnnotation'

### ISSUE THREAD

**Issue by radimk** [syself/cluster-api-provider-hetzner#657]
/kind bug

**What steps did you take and what happened:**

Build cluster with HCloud control plane (3 nodes), add several baremetal nodes. Overnight one node disconnected from cluster (control plane was unreachable for a while and node couldn't connect and its certificate expired, after that I couldn't find a way how to put it back, I can file another issues about this). I drained, cordoned and delete the node. After that CAPH is continually crashing (I can't say for sure but I am almost sure that's what happened). Now I cannot delete any of `hetznerbaremetalmachine.infrastructure.cluster.x-k8s.io/gc1-md-1-cqv6t machine.cluster.x-k8s.io/gc1-md-1-85cb576456-jvqbr hetznerbaremetalhost.infrastructure.cluster.x-k8s.io/aac17` and I cannot add new node because CAPH webhook is not working.

**What did you expect to happen:**

I thought that CAPH will reconcile. Maybe I should have deleted baremetalhost first and expect that it will propagate and delete the node but there is no protection against that.

**Anything else you would like to add:**

Now I am looking for a way how to patch remaining object to get CAPH working again. `kubectl delete hetznerbaremetalmachine.infrastructure.cluster.x-k8s.io/gc1-md-1-cqv6t machine.cluster.x-k8s.io/gc1-md-1-85cb576456-jvqbr hetznerbaremetalhost.infrastructure.cluster.x-k8s.io/aac17` is stuck waiting. Can I remove some finalizers / skip hooks and expect that the situation will improve?

Related part of CAPH log
```
{"level":"ERROR","time":"2023-03-10T18:38:07.655Z","file":"remediation/remediation.go:61","message":"unable to find a host for unhealthy machine","controller":"hetznerbaremetalremediation","controllerGroup":"infrastructure.cluster.x-k8s.io","controllerKind":"HetznerBareMetalRemediation","HetznerBareMetalRemediation":{"name":"gc1-md-1-85cb576456-jvqbr","namespace":"cluster"},"namespace":"cluster","name":"gc1-md-1-85cb576456-jvqbr","reconcileID":"ff17c4cf-6215-4d7e-a864-f19c8f991a36","HetznerBareMetalRemediation":{"name":"gc1-md-1-85cb576456-jvqbr","namespace":"cluster"},"Machine":{"name":"gc1-md-1-85cb576456-jvqbr","namespace":"cluster"},"HetznerBareMetalMachine":{"name":"gc1-md-1-cqv6t","namespace":"cluster"},"Cluster":{"name":"gc1","namespace":"cluster"},"HetznerCluster":{"name":"gc1","namespace":"cluster"},"error":"unable to get gc1-md-1-cqv6t HostAnnotation","stacktrace":"github.com/syself/cluster-api-provider-hetzner/pkg/services/baremetal/remediation.(*Service).Reconcile\n\t/src/cluster-api-provider-hetzner/pkg/services/baremetal/remediation/remediation.go:61\ngithub.com/syself/cluster-api-provider-hetzner/controllers.(*HetznerBareMetalRemediationReconciler).reconcileNormal\n\t/src/cluster-api-provider-hetzner/controllers/hetznerbaremetalremediation_controller.go:160\ngithub.com/syself/cluster-api-provider-hetzner/controllers.(*HetznerBareMetalRemediationReconciler).Reconcile\n\t/src/cluster-api-provider-hetzner/controllers/hetznerbaremetalremediation_controller.go:152\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/src/cluster-api-provider-hetzner/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:121\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/src/cluster-api-provider-hetzner/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:320\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/src/cluster-api-provider-hetzner/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:273\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/src/cluster-api-provider-hetzner/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:234"}
{"level":"ERROR","time":"2023-03-10T18:28:38.710Z","file":"controller/controller.go:326","message":"Reconciler error","controller":"hetznerbaremetalremediation","controllerGroup":"infrastructure.cluster.x-k8s.io","controllerKind":"HetznerBareMetalRemediation","HetznerBareMetalRemediation":{"name":"gc1-md-1-85cb576456-jvqbr","namespace":"cluster"},"namespace":"cluster","name":"gc1-md-1-85cb576456-jvqbr","reconcileID":"38349c28-9ea9-4dfe-86ea-d5e2a9ff34f1","error":"failed to reconcile server for BareMetalRemediation cluster/gc1-md-1-85cb576456-jvqbr: unable to find a host for unhealthy machine: unable to get gc1-md-1-cqv6t HostAnnotation","errorVerbose":"unable to get gc1-md-1-cqv6t HostAnnotation\nunable to find a host for unhealthy machine\ngithub.com/syself/cluster-api-provider-hetzner/pkg/services/baremetal/remediation.(*Service).Reconcile\n\t/src/cluster-api-provider-hetzner/pkg/services/baremetal/remediation/remediation.go:62\ngithub.com/syself/cluster-api-provider-hetzner/controllers.(*HetznerBareMetalRemediationReconciler).reconcileNormal\n\t/src/cluster-api-provider-hetzner/controllers/hetznerbaremetalremediation_controller.go:160\ngithub.com/syself/cluster-api-provider-hetzner/controllers.(*HetznerBareMetalRemediationReconciler).Reconcile\n\t/src/cluster-api-provider-hetzner/controllers/hetznerbaremetalremediation_controller.go:152\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/src/cluster-api-provider-hetzner/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:121\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/src/cluster-api-provider-hetzner/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:320\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/src/cluster-api-provider-hetzner/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:273\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/src/cluster-api-provider-hetzner/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:234\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1594\nfailed to reconcile server for BareMetalRemediation cluster/gc1-md-1-85cb576456-jvqbr\ngithub.com/syself/cluster-api-provider-hetzner/controllers.(*HetznerBareMetalRemediationReconciler).reconcileNormal\n\t/src/cluster-api-provider-hetzner/controllers/hetznerbaremetalremediation_controller.go:161\ngithub.com/syself/cluster-api-provider-hetzner/controllers.(*HetznerBareMetalRemediationReconciler).Reconcile\n\t/src/cluster-api-provider-hetzner/controllers/hetznerbaremetalremediation_controller.go:152\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/src/cluster-api-provider-hetzner/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:121\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/src/cluster-api-provider-hetzner/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:320\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/src/cluster-api-provider-hetzner/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:273\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/src/cluster-api-provider-hetzner/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:234\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1594","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/src/cluster-api-provider-hetzner/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:326\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/src/cluster-api-provider-hetzner/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:273\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/src/cluster-api-provider-hetzner/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:234"}
...
panic: assignment to entry in nil map [recovered]
	panic: assignment to entry in nil map

goroutine 589 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
	/src/cluster-api-provider-hetzner/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:118 +0x1f4
panic({0x18948a0, 0x1d687f0})
	/usr/local/go/src/runtime/panic.go:884 +0x212
github.com/syself/cluster-api-provider-hetzner/pkg/services/baremetal/remediation.(*Service).setRebootAnnotation(0xc000a937e0, {0x1d82d58, 0xc000b08540}, 0xc000508d80, 0x12?)
	/src/cluster-api-provider-hetzner/pkg/services/baremetal/remediation/remediation.go:212 +0x159

```

Fail when adding new baremetalhost

```
$ kubectl -n cluster create -f ../infra/aac15.yaml 
Error from server (InternalError): error when creating "../infra/aac15.yaml": Internal error occurred: failed calling webhook "mutation.hetznerbaremetalhost.infrastructure.cluster.x-k8s.io": failed to call webhook: Post "https://caph-webhook-service.caph-system.svc:443/mutate-infrastructure-cluster-x-k8s-io-v1beta1-hetznerbaremetalhost?timeout=10s": no endpoints available for service "caph-webhook-service"
```

**Environment:**

- cluster-api-provider-hetzner version: ghcr.io/syself/caph:v1.0.0-beta.15, clusterapi 1.3.5
- Kubernetes version: (use `kubectl version`) both client and server 1.25.2
- OS (e.g. from `/etc/os-release`): control plane machines are build from Ubuntu 22.04, nodes run Ubuntu 20.04

**Comment by batistein** [comment]
@radimk you could try to update the caph-controller to the [nightly version](https://github.com/syself/cluster-api-provider-hetzner/pkgs/container/caph-staging/versions) `ghcr.io/syself/caph-staging:sha-a653b66` to test it out.

**Comment by radimk** [comment]
Thanks, it helped. CAPH is running now. I was able to delete orphaned machine.cluster.x-k8s.io instance and also create (provision) new server.
